# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTjlcCp13ZcK52L0P4EyMV0dOy10-Dkb

### IMPORT LIBRARY
Pada bagian ini, kita mengimpor berbagai library yang diperlukan untuk proses analisis data dan pembangunan model machine learning.
- pandas dan numpy digunakan untuk manipulasi data.
- sklearn digunakan untuk pembagian data, pemodelan, dan evaluasi.
- matplotlib.pyplot dan seaborn digunakan untuk visualisasi data.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

"""### Loading Data
Dataset diabetes.csv dimuat ke dalam variabel df menggunakan fungsi pd.read_csv(). Dataset ini berisi informasi medis pasien seperti kadar glukosa, tekanan darah, BMI, dan variabel lainnya yang digunakan untuk memprediksi kemungkinan seseorang menderita diabetes (Outcome).
"""

df = pd.read_csv("diabetes.csv")

"""### EDA
Pada tahap ini, dilakukan peninjauan awal terhadap data seperti melihat beberapa baris teratas, memeriksa tipe data dan jumlah nilai non-null, serta melihat statistik deskriptif untuk memahami distribusi dan karakteristik setiap fitur.
"""

df.head()

df.info()

df.describe(include = "all")

print("\nJumlah data duplikat:", df.duplicated().sum())

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Heatmap Korelasi Fitur')
plt.show()

"""### Data Preparation
Pada tahap ini, dilakukan pembersihan data untuk mengatasi nilai 0 pada fitur medis, Nilai tersebut diganti dengan NaN dan kemudian diimputasi menggunakan nilai median agar data tetap representatif dan tidak terdistorsi oleh outlier
"""

cols_with_zero = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
for col in cols_with_zero:
    df[col].replace(0, np.nan, inplace=True)

df.fillna(df.median(), inplace=True)

"""### Split Dataset"""

X = df.drop('Outcome', axis=1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""### Model Training"""

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

"""### Prediction and Evaluation
Evaluasi ini memberikan gambaran seberapa baik model memprediksi kemungkinan diabetes berdasarkan fitur medis yang tersedia.
"""

y_pred = model.predict(X_test)

print("\nAkurasi:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

importances = model.feature_importances_
features = X.columns
feat_imp = pd.Series(importances, index=features).sort_values(ascending=False)

plt.figure(figsize=(10,6))
feat_imp.plot(kind='bar')
plt.title('Feature Importance')
plt.ylabel('Importance')
plt.tight_layout()
plt.show()

